import { MusicVideo } from "@/types";

export const messages: string[] = [
    "This year will bring you endless joy and prosperity.",
    "A fresh start awaits, filled with opportunities to shine.",
    "You’re destined for greatness in 2025—embrace it.",
    "Every step you take this year will lead you closer to your dreams.",
    "A year of happiness and fulfillment lies ahead.",
    "Get ready to conquer challenges and celebrate victories.",
    "Your 2025 will be a canvas of bright colors and success.",
    "This is the year you’ll turn your ideas into reality.",
    "Love and laughter will follow you wherever you go.",
    "You’ll find beauty in even the smallest moments.",
    "A surprise adventure will make this year unforgettable.",
    "Your efforts will be rewarded in the best ways possible.",
    "2025 is your time to rise and shine like never before.",
    "Every day will bring new reasons to smile.",
    "You’re entering a year filled with blessings and opportunities.",
    "Growth and discovery will define your journey this year.",
    "Your hard work will open doors you never imagined.",
    "This year, your heart will be filled with gratitude and peace.",
    "2025 will be your most rewarding year yet.",
    "Believe in yourself, and everything will fall into place.",
    "Unexpected joys will brighten your path.",
    "New connections will enrich your life in 2025.",
    "A sense of purpose will guide you through the year.",
    "Your courage will lead you to incredible achievements.",
    "Happiness will knock on your door when you least expect it.",
    "A breakthrough moment will redefine your goals.",
    "Serenity and clarity will be your closest companions.",
    "Your resilience will inspire those around you.",
    "A newfound passion will ignite your spirit.",
    "Each sunrise will bring you closer to your dreams.",
    "The love you share will multiply tenfold this year.",
    "2025 will be the year you embrace your true potential.",
    "Laughter will echo through your days, bringing warmth to your soul.",
    "Success will follow you like a loyal friend.",
    "You’ll discover strengths you didn’t know you had.",
    "Peace will fill your home and heart throughout the year.",
    "Your dreams will take flight and soar beyond your imagination.",
    "Challenges will transform into stepping stones to greatness.",
    "2025 is the year to celebrate your uniqueness.",
    "You’ll achieve more than you ever thought possible.",
    "Kindness will flow into your life from unexpected sources.",
    "Joyful surprises will make this year extraordinary.",
    "Your creativity will bloom in ways you never expected.",
    "A new chapter of your story begins now—write it boldly.",
    "Confidence will be your greatest asset in 2025.",
    "This year will be filled with laughter, love, and light.",
    "The universe has amazing plans for you—trust the process.",
    "Your efforts will inspire others to dream big.",
    "Friendship and love will enrich your life beyond measure.",
    "The lessons you learn will shape a brighter future.",
    "Every obstacle will become an opportunity to grow.",
    "A sense of purpose will fill your days with meaning.",
    "You’ll leave a lasting impression on everyone you meet.",
    "Courage and determination will carry you through 2025.",
    "New adventures will bring excitement and discovery.",
    "This year will be your time to shine brighter than ever.",
    "Small victories will build up to monumental successes.",
    "Your kindness will be returned to you tenfold.",
    "A new beginning awaits—embrace it with open arms.",
    "Strength and resilience will be your guiding forces.",
    "You’ll find joy in the unexpected moments of life.",
    "Your journey this year will inspire others to dream big.",
    "Gratitude will fill your heart with endless peace.",
    "A year of abundance and prosperity is on its way.",
    "You’ll turn challenges into opportunities with grace.",
    "The best is yet to come—believe it and achieve it.",
    "Every choice you make will lead to positive outcomes.",
    "Success will follow your unwavering determination.",
    "You’ll unlock potential you never knew existed.",
    "This is your year to create the life you’ve always wanted.",
    "Love and compassion will be your guiding stars.",
    "A dream you’ve cherished will come true in 2025.",
    "This year, your passion will inspire those around you.",
    "A spark of creativity will light up your journey.",
    "Your efforts will bring rewards beyond your expectations.",
    "2025 will be the year you find balance and harmony.",
    "Your positivity will attract wonderful opportunities.",
    "A year of happiness and self-discovery awaits.",
    "Your kindness will bring light into the lives of many.",
    "You’ll achieve clarity in your goals and dreams.",
    "A sense of adventure will make this year unforgettable.",
    "Your determination will transform dreams into reality.",
    "Each day will bring new chances to grow and thrive.",
    "You’ll find joy in the little things that make life beautiful.",
    "This is your time to shine and show the world your brilliance.",
    "Peace and prosperity will follow you through 2025.",
    "You’ll make memories that last a lifetime.",
    "Your courage will open doors to incredible opportunities.",
    "The best days of your life are just around the corner.",
    "Every effort will bring you closer to your dreams.",
    "Your story will inspire countless others this year.",
    "Love and success will surround you at every turn.",
    "A sense of fulfillment will guide you throughout the year.",
];

export const fortuneBoosters: string[] = [
    "Meeting supportive and inspiring people.",
    "A chance to travel to your dream destination.",
    "Financial growth and stability.",
    "A new hobby that sparks joy.",
    "Discovering hidden talents.",
    "Strengthening bonds with loved ones.",
    "Finding your perfect work-life balance.",
    "Unlocking a major career opportunity.",
    "Achieving unexpected recognition or reward.",
    "Building meaningful and lasting friendships.",
    "A life-changing opportunity at the perfect time.",
    "Getting clarity on your true goals.",
    "Making a decision that changes your life for the better.",
    "Embracing a healthier and more fulfilling lifestyle.",
    "Discovering a book or movie that inspires you deeply.",
    "Success in a project you’ve been working hard on.",
    "Receiving an unexpected gift or surprise.",
    "A windfall or financial bonus.",
    "Strengthening your emotional resilience.",
    "Finding the courage to take risks and succeed.",
    "Turning an obstacle into a stepping stone.",
    "The start of a journey to self-discovery.",
    "A creative idea that leads to success.",
    "Discovering the beauty of simplicity in life.",
    "Building a home filled with peace and warmth.",
    "Exploring a new culture or cuisine.",
    "Establishing a positive daily routine.",
    "Discovering a passion you didn’t know you had.",
    "Reconnecting with an old friend or family member.",
    "Becoming part of a community that feels like home.",
    "Making a significant positive impact on others.",
    "A spontaneous trip or adventure.",
    "Overcoming a challenge and feeling proud.",
    "Learning a skill that changes your perspective.",
    "An unexpected opportunity to showcase your talents.",
    "Enjoying the fruits of your labor.",
    "A heartfelt compliment that makes your day.",
    "Falling in love or deepening a current relationship.",
    "Having your voice heard and valued.",
    "Celebrating a milestone that means the world to you.",
    "Rediscovering your inner strength.",
    "Attracting people who genuinely care about you.",
    "Receiving help at just the right moment.",
    "Starting a project that lights up your soul.",
    "Taking a leap of faith that pays off.",
    "Realizing how much you’ve grown and achieved.",
    "Achieving personal goals you set long ago.",
    "Your health and energy are improving noticeably.",
    "Strengthening your confidence through accomplishments.",
    "A moment of pure happiness and laughter.",
    "Reaching new heights in your career.",
    "Receiving love and support when you need it most.",
    "Discovering a new favorite place.",
    "Finding a mentor who inspires and guides you.",
    "Gaining clarity on your next steps.",
    "Success in a personal or professional endeavor.",
    "A relaxing and rejuvenating vacation.",
    "Gaining a deeper appreciation for life.",
    "Receiving a heartfelt thank-you from someone you helped.",
    "An inspiring conversation that changes your perspective.",
    "Progressing in a skill or passion project.",
    "Finding a treasure or keepsake that brings joy.",
    "A meaningful gesture from someone you admire.",
    "Resolving a long-standing issue or conflict.",
    "Getting recognized for your efforts.",
    "Discovering a new favorite song or playlist.",
    "Receiving a token of appreciation from someone close.",
    "Seeing your hard work pay off in unexpected ways.",
    "Strengthening your connection with nature.",
    "A surprise visit or reunion with someone dear.",
    "Achieving a sense of peace and fulfillment.",
    "Unlocking opportunities through networking.",
    "Embracing a new chapter with optimism.",
    "Feeling deeply connected to your surroundings.",
    "A positive change in your daily environment.",
    "Finding a new way to express yourself creatively.",
    "Having your dreams align perfectly with reality.",
    "A random act of kindness brightening your day.",
    "Discovering a hidden gem in your neighborhood.",
    "Gaining respect and admiration from peers.",
    "Your intuition guides you to the right choices.",
    "Forming a bond with someone who truly understands you.",
    "Having a breakthrough moment in self-awareness.",
    "A goal you thought was out of reach becoming attainable.",
    "The start of a journey to greater happiness.",
    "Learning lessons that empower you to move forward.",
    "A heartfelt apology bringing closure.",
    "Witnessing or being part of a miracle.",
    "A creative spark that leads to something extraordinary.",
    "Enjoying the quiet moments of life.",
    "Receiving validation for your hard work and dedication.",
    "Celebrating small victories that bring joy.",
    "The realization that you are exactly where you need to be.",
];

export const stayAlerts: string[] = [
    "Overcommitting to too many projects.",
    "Ignoring your gut feelings.",
    "Neglecting your physical and mental health.",
    "Overspending on non-essential items.",
    "Relying too heavily on others for support.",
    "Avoiding difficult conversations.",
    "Letting fear of failure hold you back.",
    "Trusting someone who doesn’t have your best interests at heart.",
    "Being overly critical of yourself.",
    "Overindulging in unhealthy habits.",
    "Forgetting to celebrate small victories.",
    "Staying in toxic environments for too long.",
    "Ignoring red flags in relationships or work.",
    "Being too rigid in your plans and goals.",
    "Procrastinating on important tasks.",
    "Taking on unnecessary stress.",
    "Making decisions without considering long-term consequences.",
    "Neglecting important relationships.",
    "Failing to set clear boundaries.",
    "Letting perfectionism prevent you from starting.",
    "Acting impulsively in financial matters.",
    "Miscommunication causing unnecessary conflicts.",
    "Ignoring feedback that could help you improve.",
    "Spreading yourself too thin.",
    "Missing out on opportunities due to hesitation.",
    "Overthinking every decision.",
    "Comparing yourself to others too much.",
    "Allowing negativity to dominate your thoughts.",
    "Letting pride prevent you from asking for help.",
    "Dwelling on past mistakes.",
    "Avoiding challenges that could help you grow.",
    "Neglecting your personal time and space.",
    "Being too passive in pursuing your goals.",
    "Overlooking small signs of progress.",
    "Disregarding the advice of trusted mentors.",
    "Failing to manage your time effectively.",
    "Underestimating your own capabilities.",
    "Avoiding risks that are worth taking.",
    "Staying in your comfort zone for too long.",
    "Sacrificing your values to fit in.",
    "Getting caught up in unnecessary drama.",
    "Ignoring the importance of rest and relaxation.",
    "Failing to prioritize self-care.",
    "Being too quick to judge others.",
    "Overloading yourself with responsibilities.",
    "Neglecting to plan for the future.",
    "Becoming overly dependent on technology.",
    "Avoiding feedback out of fear of criticism.",
    "Allowing fear to dictate your decisions.",
    "Getting stuck in unhealthy routines.",
    "Taking loved ones for granted.",
    "Missing deadlines due to poor time management.",
    "Holding onto grudges that weigh you down.",
    "Avoiding opportunities to learn and grow.",
    "Letting small setbacks ruin your mood.",
    "Failing to adapt to new circumstances.",
    "Losing focus on your long-term vision.",
    "Allowing distractions to derail your plans.",
    "Relying on shortcuts instead of doing the hard work.",
    "Putting others’ needs before your own too often.",
    "Being too hard on yourself after mistakes.",
    "Overestimating your ability to multitask.",
    "Ignoring signs of burnout.",
    "Avoiding taking responsibility for your actions.",
    "Staying silent when your voice needs to be heard.",
    "Allowing fear of judgment to stifle creativity.",
    "Getting stuck in toxic habits or patterns.",
    "Failing to maintain a healthy work-life balance.",
    "Being resistant to constructive criticism.",
    "Spending too much time on social media.",
    "Letting negative opinions influence your decisions.",
    "Straying from your core values.",
    "Losing sight of your goals during setbacks.",
    "Avoiding networking opportunities.",
    "Overestimating how much you can handle alone.",
    "Neglecting to express gratitude.",
    "Forgetting to reward yourself for hard work.",
    "Being overly skeptical of good opportunities.",
    "Allowing jealousy to cloud your judgment.",
    "Putting off decisions that require immediate attention.",
    "Overreaching without proper preparation.",
    "Not listening to your body’s needs.",
    "Disregarding the importance of patience.",
    "Rushing through tasks without focus.",
    "Failing to keep promises you’ve made to yourself.",
    "Underestimating the value of rest and leisure.",
    "Taking criticism too personally.",
    "Letting small irritations ruin your day.",
    "Neglecting to learn from your mistakes.",
    "Overthinking how others perceive you.",
    "Becoming overly complacent in your comfort zone.",
    "Losing perspective on what truly matters.",
    "Failing to seek clarity when confused.",
    "Ignoring opportunities for collaboration.",
    "Holding yourself back out of fear of rejection.",
    "Focusing too much on outcomes rather than the process.",
];

export const unexpectedFortunes: string[] = [
    "Practice daily gratitude to shift your mindset.",
    "Meditate to calm your thoughts and attract positive energy.",
    "Create a vision board to focus on your goals.",
    "Declutter your living space to invite new opportunities.",
    "Carry a lucky charm that holds personal meaning.",
    "Write down affirmations and repeat them daily.",
    "Avoid overthinking and trust the process.",
    "Surround yourself with positive and supportive people.",
    "Reflect on past successes to regain confidence.",
    "Learn from setbacks and apply the lessons moving forward.",
    "Practice mindfulness to stay present and focused.",
    "Set achievable goals to build momentum.",
    "Keep a journal to process negative emotions.",
    "Take small, intentional steps toward your objectives.",
    "Volunteer or help others to improve your perspective.",
    "Stay physically active to boost your mood and energy.",
    "Read motivational books to inspire new thinking.",
    "Connect with mentors who can provide guidance.",
    "Embrace failure as part of the growth process.",
    "Trust your instincts when making decisions.",
    "Take breaks when feeling overwhelmed.",
    "Maintain a healthy routine of eating, sleeping, and exercising.",
    "Avoid procrastination and tackle tasks head-on.",
    "Create a mantra to motivate yourself in tough times.",
    "Reevaluate priorities and focus on what truly matters.",
    "Take risks but calculate them carefully.",
    "Celebrate small wins to maintain a positive outlook.",
    "Practice forgiveness to release lingering negativity.",
    "Change your environment to spark fresh ideas.",
    "Try new hobbies or activities to shift your focus.",
    "Attend workshops or classes to develop new skills.",
    "Keep track of progress to remind yourself of achievements.",
    "Engage in self-care activities that recharge you.",
    "Build a network of like-minded individuals.",
    "Limit exposure to negative news or social media.",
    "Take responsibility for your actions and choices.",
    "Focus on solutions rather than dwelling on problems.",
    "Use visualization techniques to imagine success.",
    "Take deep breaths to manage stress effectively.",
    "Prioritize quality over quantity in commitments.",
    "Develop a daily gratitude practice to attract positivity.",
    "Explore creative outlets like art or writing.",
    "Make time for loved ones to strengthen connections.",
    "Avoid unnecessary drama or conflicts.",
    "Reflect on your journey and celebrate progress.",
    "Incorporate daily affirmations into your routine.",
    "Invest in your personal and professional growth.",
    "Reassess your goals and make adjustments as needed.",
    "Find humor in challenging situations to lighten the mood.",
    "Stay adaptable in the face of unexpected changes.",
    "Take walks in nature to reset your mindset.",
    "Set boundaries to protect your energy.",
    "Practice self-compassion and be kind to yourself.",
    "Reframe challenges as opportunities for growth.",
    "Take one day at a time to reduce overwhelm.",
    "Focus on your strengths and use them to your advantage.",
    "Seek professional advice when facing tough decisions.",
    "Travel or explore new places for a fresh perspective.",
    "Use music to uplift and motivate yourself.",
    "Acknowledge your emotions and give yourself time to heal.",
    "Learn to say no when necessary to avoid overcommitment.",
    "Create a structured daily plan to stay on track.",
    "Experiment with positive rituals to start your day.",
    "Practice patience during challenging periods.",
    "Focus on building habits that align with your goals.",
    "Avoid toxic relationships that drain your energy.",
    "Seek clarity in your communication to avoid misunderstandings.",
    "Take time to appreciate life’s small pleasures.",
    "Learn from the experiences of others.",
    "Stay open to feedback and constructive criticism.",
    "Avoid rushing into major decisions without proper thought.",
    "Revisit your core values and align your actions with them.",
    "Take care of your mental health through therapy or support groups.",
    "Focus on what you can control and let go of the rest.",
    "Stay disciplined in your efforts to achieve long-term success.",
    "Engage in deep breathing exercises to reduce anxiety.",
    "Reflect on your dreams and take steps to pursue them.",
    "Create a daily ritual that brings you joy.",
    "Experiment with meditation or yoga for relaxation.",
    "Use setbacks as stepping stones to greater achievements.",
    "Decline opportunities that don’t serve your ultimate goals.",
    "Strengthen relationships by showing appreciation to others.",
    "Believe in your ability to turn bad luck into good fortune.",
    "Build resilience by facing challenges head-on.",
    "Find inspiration in the success stories of others.",
    "Avoid overanalyzing situations that are out of your control.",
    "Practice empathy and kindness in your interactions.",
    "Keep your sense of humor even in tough times.",
    "Focus on the bigger picture to maintain perspective.",
    "Stay hopeful and optimistic about the future.",
    "Break down goals into smaller, manageable tasks.",
    "Trust the timing of your life’s journey.",
    "Avoid self-sabotaging behaviors or thought patterns.",
    "Celebrate your unique qualities and talents.",
    "Stay humble and grounded in your achievements.",
    "Visualize positive outcomes and work toward them.",
    "Approach challenges with curiosity rather than fear.",
];

export const musicVideos: MusicVideo[] = [
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/gOtfJ151ue4",
        title: "Tết Đong Đầy | KHOA x Kay Tran x Duck V | HOMIE BOIZ OFFICIAL",
    },
    {
        width: 907,
        height: 380,
        src: "https://www.youtube.com/embed/vTJdVE_gjI0",
        title: "Đen x JustaTee - Đi Về Nhà (M/V)",
    },
    {
        width: 746,
        height: 319,
        src: "https://www.youtube.com/embed/iy53wPnNCYU",
        title: "Đi Để Trở Về - Soobin Hoàng Sơn | Official Music Video",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/VSyL6RSiJbs",
        title: "gameboy",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/ekr2nIex040",
        title: "ROSÉ & Bruno Mars - APT. (Official Music Video)",
    },
    {
        width: 540,
        height: 360,
        src: "https://www.youtube.com/embed/abPmZCZZrFA",
        title: "SƠN TÙNG M-TP | ĐỪNG LÀM TRÁI TIM ANH ĐAU | OFFICIAL MUSIC VIDEO",
    },
    {
        width: 540,
        height: 360,
        src: "https://www.youtube.com/embed/RPQO37npkDY",
        title: "Thịnh Suy - Nói Gì Nữa (Music Video)",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/vkIe0qqYzVs",
        title: "Đen – Triệu điều nhỏ xíu xiêu lòng ft. Kim Long (M/V)",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/SWXpFD6uWxk",
        title: "Hoàng Thuỳ Linh & Thanh Bùi - không một bài hát nào có thể diễn tả cảm xúc của em lúc này.",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/LcniJZRXf2c",
        title: "dính - bồ em",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/2S24-y0Ij3Y",
        title: "BLACKPINK - 'Kill This Love' M/V",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/bB3-CUMERIU",
        title: "JENNIE - Mantra (Official Music Video)",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/EEhZAHZQyf4",
        title: "Ariana Grande - thank u, next (Official Lyric Video)",
    },
    {
        width: 760,
        height: 380,
        src: "https://www.youtube.com/embed/eVli-tstM5E",
        title: "Sabrina Carpenter - Espresso (Official Video)",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/GTWqwSNQCcg",
        title: "'City of Stars' (Duet ft. Ryan Gosling, Emma Stone - La La Land Original Motion Picture Soundtrack)",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/6eLnnZnXcX8",
        title: "ABBA - Happy New Year (Official Lyric Video)",
    },
    {
        width: 637,
        height: 360,
        src: "https://www.youtube.com/embed/7KbfG11KO_s",
        title: "Thế Bảo - Anh Chỉ Biết Ngồi Hát (Official MV)",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/UamN4zQDgPY",
        title: "PHÁP KIỀU - CUNG TÊN TÌNH YÊU  (prod.By Jase | OFFICIAL MUSIC VIDEO",
    },
    {
        width: 762,
        height: 319,
        src: "https://www.youtube.com/embed/i0nd3NPJ4MI",
        title: "HIEUTHUHAI - Không Thể Say (prod. by Kewtiie l Official Video",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/PMivT7MJ41M",
        title: "Bruno Mars - That’s What I Like [Official Music Video]",
    },
];
