import { MusicVideo, Refer } from "@/types";

export const messages: string[] = [
    "2025 will bring you endless joy and prosperity.",
    "A fresh start awaits, filled with opportunities to shine.",
    "Every step you take this year will lead you closer to your dreams.",
    "Get ready to conquer challenges and celebrate victories.",
    "Your efforts will be rewarded in the best ways possible.",
    "This year is your runway — just shine as you are.",
    "2025 is your time to rise and shine like never before.",
    "Every day will bring new reasons to smile.",
    "Growth and discovery will define your journey this year.",
    "Your hard work will open doors you never imagined.",
    "Unexpected joys will brighten your path.",
    "Your courage will lead you to incredible achievements.",
    "Your resilience will inspire those around you.",
    "Each sunrise will bring you closer to your dreams.",
    "2025 will be the year you embrace your true potential.",
    "Laughter will echo through your days, bringing warmth to your soul.",
    "Success will follow you like a loyal friend.",
    "You’ll discover strengths you didn’t know you had.",
    "Peace will fill your home and heart throughout the year.",
    "Your dreams will take flight and soar beyond your imagination.",
    "Challenges will transform into stepping stones to greatness.",
    "You’ll achieve more than you ever thought possible.",
    "Joyful surprises will make this year extraordinary.",
    "Your creativity will bloom in ways you never expected.",
    "Confidence will be your greatest asset in 2025.",
    "The universe has amazing plans for you.",
    "Your efforts will inspire others to dream big.",
    "Friendship and love will enrich your life.",
    "The lessons you learn will shape a brighter future.",
    "Every obstacle will become an opportunity to grow.",
    "Courage and determination will carry you through 2025.",
    "New adventures will bring excitement and discovery.",
    "This year will be your time to shine brighter than ever.",
    "Small victories will build up to monumental successes.",
    "Strength and resilience will be your guiding forces.",
    "Your journey this year will inspire others to dream big.",
    "A year of abundance and prosperity is on its way.",
    "You’ll turn challenges into opportunities with grace.",
    "The best is yet to come — believe it and achieve it.",
    "Success will follow your unwavering determination.",
    "You’ll unlock potential you never knew existed.",
    "This is your year to create the life you’ve always wanted.",
    "Love and compassion will be your guiding stars.",
    "A dream you’ve cherished will come true in 2025.",
    "This year, your passion will inspire those around you.",
    "Your efforts will bring rewards beyond your expectations.",
    "Your positivity will attract wonderful opportunities.",
    "A year of happiness and self-discovery awaits.",
    "Your determination will transform dreams into reality.",
    "Each day will bring new chances to grow and thrive.",
    "You’ll find joy in the little things that make life beautiful.",
    "Peace and prosperity will follow you through 2025.",
    "Your courage will open doors to incredible opportunities.",
    "Every effort will bring you closer to your dreams.",
    "Love and success will surround you at every turn.",
    "You’ll leave a lasting impression on everyone you meet.",
];

export const fortuneBoosters: string[] = [
    "New connections with inspiring and supportive people.",
    "A trip to your dream destination.",
    "A new hobby that brings joy.",
    "Glow-up skincare.",
    "Karaoke night with friends.",
    "Stronger bonds with loved ones.",
    "The perfect balance between work and life.",
    "Unexpected recognition for hard work.",
    "Meaningful and lasting friendships.",
    "A timely opportunity that changes everything.",
    "A healthier and more fulfilling lifestyle.",
    "A book or movie that inspires deeply.",
    "An unexpected gift or surprise.",
    "A financial bonus or windfall.",
    "Courage to take risks and achieve success.",
    "A journey to self-discovery.",
    "A perfect ramen will do you good.",
    "The beauty of simplicity in daily life.",
    "A home filled with peace and warmth.",
    "New experiences with a different culture or cuisine.",
    "A perfect iced coffee.",
    "A newly discovered passion.",
    "A reunion with an old friend or family member.",
    "A spontaneous adventure.",
    "A heartfelt compliment that brightens your day.",
    "A leap of faith resulting in success.",
    "Noticeable improvements in health and energy.",
    "The confidence gained from achievements.",
    "A moment of pure happiness.",
    "A special place that feels like home.",
    "Guidance from an inspiring mentor.",
    "Success in professional or personal goals.",
    "A relaxing and refreshing vacation.",
    "Gratitude from someone you’ve helped.",
    "A meaningful conversation with fresh insights.",
    "A heartfelt gesture from someone admired.",
    "A song that resonates with your soul.",
    "A token of love from a close friend.",
    "A breakthrough that changes perspectives.",
    "Support from unexpected sources.",
    "Recognition from peers and colleagues.",
    "A sense of achievement in your journey.",
    "A moment of manifest.",
    "A connection with nature’s beauty.",
    "A perfect snack for a movie night.",
    "A cozy night in with your favorite book.",
    "A handwritten letter from a loved one.",
    "The discovery of a song you can’t stop replaying.",
    "A compliment from a colleague that boosts your confidence.",
    "A clear night sky filled with stars.",
    "The smell of fresh flowers.",
    "A funny meme that makes your day.",
];

export const stayAlerts: string[] = [
    "Overcommitting to too many projects.",
    "Ignoring your gut feelings.",
    "Neglecting your physical and mental health.",
    "Overspending on non-essential items.",
    "Relying too heavily on others for support.",
    "Letting fear of failure hold you back.",
    "Trusting someone who doesn’t have your best interests at heart.",
    "Being overly critical of yourself.",
    "Overindulging in unhealthy habits.",
    "Forgetting to celebrate small victories.",
    "Staying in toxic environments for too long.",
    "Ignoring red flags in relationships or work.",
    "Procrastinating on important tasks.",
    "Taking on unnecessary stress.",
    "Making decisions without considering long-term consequences.",
    "Neglecting important relationships.",
    "Failing to set clear boundaries.",
    "Letting perfectionism prevent you from starting.",
    "Acting impulsively in financial matters.",
    "Miscommunication causing unnecessary conflicts.",
    "Ignoring feedback that could help you improve.",
    "Missing out on opportunities due to hesitation.",
    "Overthinking every decision.",
    "Comparing yourself to others too much.",
    "Allowing negativity to dominate your thoughts.",
    "Letting pride prevent you from asking for help.",
    "Dwelling on past mistakes.",
    "Avoiding challenges that could help you grow.",
    "Being too passive in pursuing your goals.",
    "Disregarding the advice of trusted mentors.",
    "Failing to manage your time effectively.",
    "Underestimating your capabilities.",
    "Avoiding risks that are worth taking.",
    "Staying in your comfort zone for too long.",
    "Getting caught up in unnecessary drama.",
    "Ignoring the importance of relaxation.",
    "Failing to prioritize self-care.",
    "Being too quick to judge others.",
    "Overloading yourself with responsibilities.",
    "Neglecting to plan for the future.",
    "Becoming overly dependent on technology.",
    "Allowing fear to dictate your decisions.",
    "Getting stuck in unhealthy routines.",
    "Taking love for granted.",
    "Missing deadlines due to poor time management.",
    "Avoiding opportunities to learn and grow.",
    "Failing to adapt to new circumstances.",
    "Losing focus on your long-term vision.",
    "Allowing distractions to derail your plans.",
    "Relying on shortcuts instead of doing the hard work.",
    "Putting others’ needs before your own too often.",
    "Being too hard on yourself after mistakes.",
    "Overestimating your ability to multitask.",
    "Ignoring signs of burnout.",
];

export const refers: Refer[] = [
    {
        description:
            "You can boost your luck in 2025 by referring a friend for",
        title: "HubSpot CRM Specialist",
        url: "https://jobs.lever.co/nfq/1859aefe-ae55-4f19-b01f-20e4f8b74a4c",
    },
    {
        description:
            "Financial luck may come your way if you refer a friend for",
        title: "Project Manager - Data",
        url: "https://jobs.lever.co/nfq/5a5e0ffe-c13c-4e4e-bb42-8876d5c7c8b3",
    },
    {
        description: "You can attract good luck by referring a friend for",
        title: "QC Automation Engineer",
        url: "https://jobs.lever.co/nfq/c817790a-5a07-4380-a6fb-65d2915b3b1c",
    },
    {
        description: "Brighten your 2025 by referring a friend for",
        title: "Chief Financial Officer (CFO)",
        url: "https://jobs.lever.co/nfq/0b031f57-f336-49a8-ba8d-87316abc93fb",
    },
    {
        description: "Luck is on the way if you refer a friend for",
        title: "Executive Assistant",
        url: "https://jobs.lever.co/nfq/dae05a44-2078-4c46-b1d6-6913f66c8c75",
    },
    {
        description: "Set the stage for success by referring a friend for",
        title: "Talent Acquisition Executive",
        url: "https://jobs.lever.co/nfq/c66552ce-3d1e-4804-8bdb-499ec4d7db8d",
    },
    {
        description:
            "You can boost your luck in 2025 by referring a friend for",
        title: "Head of Business Unit",
        url: "https://jobs.lever.co/nfq/d73a93c7-eef8-4935-9c06-26b63978dc70",
    },
];

export const musicVideos: MusicVideo[] = [
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/gOtfJ151ue4",
        title: "Tết Đong Đầy | KHOA x Kay Tran x Duck V | HOMIE BOIZ OFFICIAL",
    },
    {
        width: 907,
        height: 380,
        src: "https://www.youtube.com/embed/vTJdVE_gjI0",
        title: "Đen x JustaTee - Đi Về Nhà (M/V)",
    },
    {
        width: 746,
        height: 319,
        src: "https://www.youtube.com/embed/iy53wPnNCYU",
        title: "Đi Để Trở Về - Soobin Hoàng Sơn | Official Music Video",
    },
    {
        width: 702,
        height: 395,
        src: "https://www.youtube.com/embed/P01O1As5hLE",
        title: "LISA - 'MONEY' M/V",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/ekr2nIex040",
        title: "ROSÉ & Bruno Mars - APT. (Official Music Video)",
    },
    {
        width: 639,
        height: 479,
        src: "https://www.youtube.com/embed/xypzmu5mMPY",
        title: "SƠN TÙNG M-TP | MUỘN RỒI MÀ SAO CÒN | OFFICIAL MUSIC VIDEO",
    },
    {
        width: 639,
        height: 479,
        src: "https://www.youtube.com/embed/OqdA6DKV1Fs",
        title: "THICHTHICH - PHƯƠNG LY | OFFICIAL MV",
    },
    {
        width: 702,
        height: 294,
        src: "https://www.youtube.com/embed/UVbv-PJXm14",
        title: "Đen - Mang Tiền Về Cho Mẹ ft. Nguyên Thảo (M/V)",
    },
    {
        width: 702,
        height: 395,
        src: "https://www.youtube.com/embed/I3RICWXA_3U",
        title: "Anh Đánh Rơi Người Yêu Này - Andiez ft. AMEE | OST #TTVKOBE",
    },
    {
        width: 480,
        height: 360,
        src: "https://www.youtube.com/embed/LcniJZRXf2c",
        title: "dính - bồ em",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/2S24-y0Ij3Y",
        title: "BLACKPINK - 'Kill This Love' M/V",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/bB3-CUMERIU",
        title: "JENNIE - Mantra (Official Music Video)",
    },
    {
        width: 702,
        height: 395,
        src: "https://www.youtube.com/embed/QYh6mYIJG2Y",
        title: "Ariana Grande - 7 rings (Official Video)",
    },
    {
        width: 760,
        height: 380,
        src: "https://www.youtube.com/embed/eVli-tstM5E",
        title: "Sabrina Carpenter - Espresso (Official Video)",
    },
    {
        width: 702,
        height: 395,
        src: "https://www.youtube.com/embed/26jc2_YprdA",
        title: "[Lyrics + Vietsub] Flying, Deep In The Night || Onew, Suhyun (AKMU)",
    },
    {
        width: 702,
        height: 395,
        src: "https://www.youtube.com/embed/j7_lSP8Vc3o",
        title: "2NE1 - 내가 제일 잘 나가(I AM THE BEST) M/V",
    },
    {
        width: 637,
        height: 360,
        src: "https://www.youtube.com/embed/7KbfG11KO_s",
        title: "Thế Bảo - Anh Chỉ Biết Ngồi Hát (Official MV)",
    },
    {
        width: 702,
        height: 395,
        src: "https://www.youtube.com/embed/Pys2iOT9rpw",
        title: "WEAN – shhhhhhh.. feat tlinh (Official Lyrics Video)",
    },
    {
        width: 762,
        height: 319,
        src: "https://www.youtube.com/embed/i0nd3NPJ4MI",
        title: "HIEUTHUHAI - Không Thể Say (prod. by Kewtiie) l Official Video",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/PMivT7MJ41M",
        title: "Bruno Mars - That's What I Like [Official Music Video]",
    },
    {
        width: 702,
        height: 395,
        src: "https://www.youtube.com/embed/nfWlot6h_JM",
        title: "Taylor Swift - Shake It Off",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/m7Bc3pLyij0",
        title: "Marshmello ft. Bastille - Happier (Official Music Video)",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/HM5spXWGuBI",
        title: "Hoàng Thuỳ Linh - Gieo Quẻ (Vietnamese Concert Edition)",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/i0p1bmr0EmE",
        title: "TWICE 'What is Love?' M/V",
    },
    {
        width: 702,
        height: 294,
        src: "https://www.youtube.com/embed/eo_JVyY1Ra4",
        title: "Em Là Châu Báu - TLinh x MCK x CB | Official MV",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/9WLb1qf2kK4",
        title: "BIGDADDY x EMILY - YÊU NẮM (Official Music Video)",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/q2YUtZum9wc",
        title: "ANH LÀ NGOẠI LỆ CỦA EM - PHƯƠNG LY | OFFICIAL MV",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/sJt_i0hOugA",
        title: "HIEUTHUHAI - Exit Sign (prod. by Kewtiie) ft. marzuz [Official Lyric Video]",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/Qc7_zRjH808",
        title: "FIFTY FIFTY (피프티피프티) - 'Cupid'  Official MV",
    },
    {
        width: 702,
        height: 395,
        src: "https://www.youtube.com/embed/vkIe0qqYzVs",
        title: "Đen – Triệu điều nhỏ xíu xiêu lòng ft. Kim Long (M/V)",
    },
    {
        width: 702,
        height: 395,
        src: "https://www.youtube.com/embed/6t-MjBazs3o",
        title: "SƠN TÙNG M-TP | CÓ CHẮC YÊU LÀ ĐÂY | OFFICIAL MUSIC VIDEO",
    },
    {
        width: 702,
        height: 395,
        src: "https://www.youtube.com/embed/CHw1b_1LVBA",
        title: "MONO - Waiting For You (Album 22 - Track No.10)",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/rRUzJJ9IV4s",
        title: "Trúc Nhân | KHÔNG RA GÌ | Official MV",
    },
    {
        width: 640,
        height: 360,
        src: "https://www.youtube.com/embed/2ips2mM7Zqw",
        title: "BIGBANG - 뱅뱅뱅 (BANG BANG BANG) M/V",
    },
];

export const boxTexts: string[] = [
    "Hey, over here! Click me!",
    "Open me now! Bad luck hates this trick!",
    "Don’t forget me! I’ve got something for you! ",
];

export const unfortunate: string[] = [
    "Oh noooo, there’s no gift for you! Take a deep breath to have better luck next time.🌟",
    "Oh noooo, your gift is missing! Grab a snack to feel better and wait for your next chance.🍪",
    "Oh noooo, someone took your gift! Ask for a hug from Annie to cheer yourself up.🤗",
    "Oh noooo, someone took your gift! Ask for a hug from Ludo to ease your bad luck.",
    "Oh noooo, no gift here! Share a laugh with a colleague and get ready for your next chance.😄",
    "Oh noooo, someone has stolen your gift! Take a nap and let good luck come back to you.😴",
    "Oh noooo, your gift is gone! Take a coffee cup and get ready for better luck soon.☕",
    "Oopsss, no present here! Take a little walk and let your luck reset.👣",
    "Oh noooo, your gift is stolen! Smile big to trade your bad luck for better luck.😆",
    "Oh noooo, no gift for you! Eat something sweet to throw away your bad luck.🍩",
    "Oopsss, your gift disappeared! Keep calm and stay confident to have better luck next time.✨",
];
