export const FLOWER_WISHES = [
  {
    flower: "Mountain Laurel",
    title_1: "⛰️This is the flower of ambition and unwavering spirit.",
    title_2: "💪Mountain Laurel thrives on rocky cliffs, never letting harsh conditions stop it from reaching for the sky.",
    title_3: "🎯You are a force of nature, always pushing forward, never settling, always reaching higher. Your determination inspires those around you, proving that no mountain is too high to climb.",
    title_4: "✨Wish you endless mountains to conquer, victories to celebrate, and the strength to rise higher with every challenge.",
  },
  {
    flower: "Fawn Lily",
    title_1: "🦌This is the flower of grace and quiet confidence.",
    title_2: "🌿Hidden in the forests, the Fawn Lily doesn’t need to be the tallest or the brightest to be beautiful—it stands out by simply being itself.",
    title_3: "🌸You move through life elegantly, never needing to rush because you know your worth. You walk with quiet confidence, proving that strength doesn’t have to be loud to be powerful.",
    title_4: "💖Wish you a world that always recognizes your beauty and strength, and the peace of knowing that you are enough, exactly as you are.",
  },
  {
    flower: "Japanese Anemone",
    title_1: "🍃This is the flower of anticipation and gentle strength.",
    title_2: "🌸Graceful yet strong, the Japanese Anemone sways in the wind without breaking, reminding us that resilience is not about being unshakable, but about bending without falling.",
    title_3: "💭You are a dreamer, patiently waiting for the right moment to let your colors shine. You understand that good things take time, and you never rush the process of growth.",
    title_4: "🌷Wish you the courage to step into your power, the patience to trust the journey, and the joy of knowing that everything meant for you will arrive at exactly the right time.",
  },
  {
    flower: "Snowdrop",
    title_1: "❄️This is the flower of hope and quiet resilience.",
    title_2: "🌱The first bloom of spring, the Snowdrop pushes through the frost, whispering that even the coldest winters must come to an end.",
    title_3: "☀️You are the first light after winter, proving that even in the hardest times, new beginnings are always possible. You carry warmth in your heart, even when the world feels cold.",
    title_4: "💛Wish you the strength to keep blooming, the warmth of sunshine after the storm, and the unwavering belief that brighter days are always ahead.",
  },
  {
    flower: "Ghost Orchid",
    title_1: "👻This is the flower of rarity and silent beauty.",
    title_2: "🌿Elusive and almost impossible to find, the Ghost Orchid is a symbol of quiet elegance, proving that the most extraordinary things in life don’t need to demand attention to be noticed.",
    title_3: "🕊️You are an enigma, someone who doesn’t need to be loud to leave a lasting impression. Your presence lingers like a whisper, unforgettable and hauntingly beautiful.",
    title_4: "💖Wish you a life where your uniqueness is always appreciated and cherished, where you never have to change to fit in, because the world will always make room for something as rare as you.",
  },
  {
    flower: "Queen Anne’s Lace",
    title_1: "👑This is the flower of protection and delicate strength.",
    title_2: "🌿Named after a queen, this wildflower may look fragile, but it grows in fields and roadsides, standing strong against the wind.",
    title_3: "🕊️You are someone who brings warmth and safety to others, like a hidden guardian in a wild field. You have a heart that nurtures, a soul that protects, and a presence that comforts.",
    title_4: "💫Wish you a life where your kindness is always returned, where your heart is as full as the love you give, and where your quiet strength is always seen and appreciated.",
  },
  {
    flower: "Bleeding Heart",
    title_1: "❤️This is the flower of deep emotional connection and unspoken love.",
    title_2: "🌊Like a heart worn on the sleeve, the Bleeding Heart blooms with quiet devotion, reminding us that true feelings can’t be hidden forever.",
    title_3: "💖You are someone who loves deeply, who feels every joy and every ache with intensity. Your heart is a gift—strong, open, and unafraid of vulnerability.",
    title_4: "🎁Wish you a love that flows as freely as your heart allows, and a connection that never fades, no matter the distance or time.",
  },
  {
    flower: "Flame Azalea",
    title_1: "🌋This is the flower of determination and fiery spirit.",
    title_2: "🍂Like a wildfire in bloom, the Flame Azalea refuses to be ignored, standing tall even in the toughest conditions.",
    title_3: "🚀You are unstoppable, a force of nature who turns every setback into a reason to rise higher. Your fire doesn’t destroy—it transforms.",
    title_4: "🌟Wish you endless victories, a heart that never wavers, and a future as fierce and brilliant as you are.",
  },
  {
    flower: "Fireweed",
    title_1: "🌾This is the flower of resilience and survival.",
    title_2: "🔥Rising from the ashes after wildfires, Fireweed blooms where everything else has fallen, proving that nothing truly ends—life just begins again in new ways.",
    title_3: "💪You are someone who refuses to be defeated, who finds strength in even the hardest moments. No matter what life takes away, you always come back stronger.",
    title_4: "🌅Wish you endless rebirths, the courage to rebuild, and a future where your strength becomes your greatest victory.",
  },
  {
    flower: "Wine-Cup",
    title_1: "🍷This is the flower of elegance and quiet confidence.",
    title_2: "🌸Deep in color, rich in presence, the Wine Cup doesn’t need to demand attention—it simply exists in its own effortless grace.",
    title_3: "💃You are someone who walks through life with poise, never needing to prove your worth because it speaks for itself. Your energy is both soft and powerful, a balance that few can master.",
    title_4: "🥂Wish you a life where your quiet strength is always noticed, where your beauty never goes unnoticed, and where confidence feels as natural as breathing.",
  },
  {
    flower: "Blue Poppy",
    title_1: "💙This is the flower of imagination and dreams.",
    title_2: "🌿Like something from a fairytale, the Blue Poppy blooms in rare places, whispering of wonder, adventure, and the impossible made real.",
    title_3: "🌙You are someone who sees beyond the ordinary, who dreams in colors that others can't even imagine. Your mind is a world of its own, limitless and extraordinary.",
    title_4: "✨Wish you a life where your dreams never fade, where your creativity finds a way to bloom, and where the impossible becomes your reality.",
  },
  {
    flower: "Night Phlox",
    title_1: "🌙This is the flower of twilight magic and mystery.",
    title_2: "🌸When the world grows quiet, the Night Phlox awakens, releasing its sweet scent into the air, a reminder that beauty doesn’t always need the sun to shine.",
    title_3: "🦋You are someone who thrives in the unseen hours, who finds inspiration in moonlight, who understands that mystery is its own kind of power.",
    title_4: "🌌Wish you a journey where the stars guide you, where the night reveals its secrets, and where you always find the magic hidden in the shadows.",
  },
  {
    flower: "Jacaranda Blossom",
    title_1: "📖This is the flower of wisdom and change.",
    title_2: "💜Falling like purple rain, the Jacaranda blooms in cycles, reminding us that every ending is also a new beginning.",
    title_3: "🦉You are someone who sees the lessons in every moment, who welcomes transformation instead of fearing it. With every change, you grow stronger, wiser, and more you.",
    title_4: "🌿Wish you a journey filled with growth, a mind always open to learning, and the courage to embrace every new chapter.",
  },
  {
    flower: "Blue Ginger",
    title_1: "💎This is the flower of unusual beauty and grace.",
    title_2: "🌿Not a true ginger, yet more striking than most, the Blue Ginger teaches us that labels don’t define worth—uniqueness does.",
    title_3: "🌊You are someone who walks with effortless elegance, who carries beauty in ways that can’t be copied. You don’t try to stand out—you just do.",
    title_4: "🎁Wish you a world where your radiance is recognized, where your quiet confidence speaks louder than words, and where you always feel as valued as you truly are.",
  },
  {
    flower: "Purple Passion",
    title_1: "🔮This is the flower of spiritual enlightenment.",
    title_2: "🌿With twisting vines and intricate petals, the Passionflower blooms like a living mandala, a symbol of deep thought and higher understanding.",
    title_3: "🌱You are someone who sees beyond the surface, who searches for meaning, who finds wisdom in both silence and chaos. Your journey is not just about living—it’s about awakening.",
    title_4: "🌌Wish you a life filled with clarity, purpose, and the knowledge that everything you seek is already within you.",
  },
  {
    flower: "Angel’s Trumpet",
    title_1: "🎺This is the flower of divine guidance and protection.",
    title_2: "🌿With its heavenly scent and ethereal beauty, the Angel’s Trumpet whispers of unseen forces, of guardian angels watching over us.",
    title_3: "🕊️You are someone who walks with grace, who carries light in every step, who knows that even in the darkest moments, there is always a hand to guide you.",
    title_4: "🌟Wish you a life where you always feel protected, where you never walk alone, and where you know that you are never far from the divine.",
  },
  {
    flower: "Bat Flower (Tacca)",
    title_1: "🦇This is the flower of intrigue and mysticism.",
    title_2: "🌑Striking, dark, and otherworldly, the Bat Flower is nature’s reminder that mystery is an art, and some things are meant to be beyond understanding.",
    title_3: "🕶️You are someone who keeps people guessing, who never reveals all at once. There is power in your presence, in your silence, in the way you make people lean in just to understand you.",
    title_4: "✨Wish you a path filled with discoveries, a life where your enigma is respected, and a future where you always remain beautifully, unapologetically, you.",
  },
  {
    flower: "Aconite (Monkshood)",
    title_1: "🛡️This is the flower of protection and inner power.",
    title_2: "🌿Named after monks’ hoods, Aconite is both beautiful and dangerous, a symbol of hidden strength and the power to defend what matters.",
    title_3: "🔥You are someone who carries a quiet fire, who may seem calm but holds immense strength beneath the surface. No one sees your full power—until they need to.",
    title_4: "🦁Wish you the courage to own your strength, the wisdom to know when to wield it, and a life where you are always safe, always seen, always unstoppable.",
  },
  {
    flower: "Leopard Lily",
    title_1: "🐆This is the flower of boldness and confidence.",
    title_2: "🌿With its fierce spots and striking colors, the Leopard Lily doesn’t just grow—it demands attention, standing tall and unshaken.",
    title_3: "💪You are someone who steps into every room like you belong there. Bold, fearless, and full of fire, your confidence isn’t loud—it’s undeniable.",
    title_4: "☀️Wish you a future where you always own your power, chase every challenge, and never forget that you were born to stand out.",
  },
  {
    flower: "Crown Imperial",
    title_1: "👑This is the flower of majesty and uniqueness.",
    title_2: "🌟Regal and rare, the Crown Imperial blooms like a golden flame, standing out with a presence that’s impossible to ignore.",
    title_3: "🎭You are someone who doesn’t follow the crowd—you lead it. With your natural grace and undeniable presence, you are royalty in your own way.",
    title_4: "💫Wish you a future where you walk with confidence, where your uniqueness is celebrated, and where your throne—whatever it may be—is waiting just for you.",
  },
  {
    flower: "Fremont’s Pincushion",
    title_1: "🛠️This is the flower of resourcefulness and survival.",
    title_2: "🌾Small but mighty, Fremont’s Pincushion thrives in the toughest landscapes, proving that adaptability is its own kind of strength.",
    title_3: "🧠You are someone who finds solutions where others see obstacles. Quick-witted, inventive, and never stuck—you always find a way to rise.",
    title_4: "🚀Wish you a life where your creativity opens doors, your resilience keeps you moving, and every challenge only sharpens your skills.",
  },
  {
    flower: "Canary Bird Bush",
    title_1: "🐦This is the flower of cheerfulness and warmth.",
    title_2: "🌞With its bright yellow blooms and lively energy, the Canary Bird Bush reminds us that happiness isn’t just an emotion—it’s a choice.",
    title_3: "🎶You are someone who brings light to any room. Your energy lifts people up, your joy is infectious, and your heart is as golden as your smile.",
    title_4: "🌻Wish you endless laughter, golden days, and a life where happiness follows you like the sun.",
  },
  {
    flower: "Yellow Horned Poppy",
    title_1: "🏜️This is the flower of wild spirit and adventure.",
    title_2: "🌿Growing in rocky, windswept places, the Yellow Horned Poppy is for those who refuse to be tamed, who thrive in the unknown.",
    title_3: "🌍You are someone who craves adventure, who sees rules as suggestions, who runs towards the horizon instead of staying behind the line.",
    title_4: "🌊Wish you a journey filled with wild moments, untamed freedom, and stories that only a true explorer could tell.",
  },
  {
    flower: "Forget-Me-Not",
    title_1: "💙This is the flower of lasting love and cherished memories.",
    title_2: "🌿Tiny but powerful, forget-me-nots bloom as a reminder that some bonds and moments are too special to fade.",
    title_3: "💞You are someone who leaves an impact wherever you go. Your kindness lingers, your love stays, and your presence is unforgettable.",
    title_4: "✨Wish you a life filled with love that never fades, memories worth holding onto, and connections that stand the test of time.",
  },
  {
    flower: "Bougainvillea",
    title_1: "🔥This is the flower of passion and resilience.",
    title_2: "🌿Bright and uncontainable, bougainvillea blooms wildly, climbing higher and thriving in even the toughest conditions.",
    title_3: "🌟You are someone who refuses to be held back. Your energy is magnetic, your passion undeniable, and your spirit as untamed as nature itself.",
    title_4: "🚀Wish you a future where you never shrink yourself, where challenges only make you stronger, and where your fire never dims.",
  },
  {
    flower: "Butterfly Pea",
    title_1: "🦋This is the flower of transformation and wisdom.",
    title_2: "🌿With petals that shift colors like magic, the butterfly pea flower reminds us that change is beautiful.",
    title_3: "🔮You are someone who embraces growth, who isn’t afraid of change, and who finds wisdom in every phase of life.",
    title_4: "🌈Wish you a journey where every transformation brings you closer to your best self, where knowledge is your superpower, and where beauty is always evolving.",
  },
  {
    flower: "Siesta",
    title_1: "😴This is the flower of rest and renewal.",
    title_2: "🌿Named after the midday nap, this bloom reminds us that true growth happens when we slow down and take care of ourselves.",
    title_3: "🌙You are someone who works hard but understands the power of balance. You know when to push forward and when to rest.",
    title_4: "💆‍♀️Wish you a life filled with deep breaths, quiet moments, and the kind of rest that fuels your biggest dreams.",
  },
  {
    flower: "Hyacinth",
    title_1: "💜This is the flower of sincerity and heartfelt emotions.",
    title_2: "🌿With its rich fragrance and deep colors, the hyacinth speaks of emotions too strong for words.",
    title_3: "💌You are someone who loves deeply, who expresses your heart fearlessly, and who brings depth to every connection.",
    title_4: "🌸Wish you relationships that are real, emotions that are celebrated, and a life where you never have to hold back what you feel.",
  },
  {
    flower: "Plumeria",
    title_1: "🌺This is the flower of positivity and joy.",
    title_2: "🌴With its tropical fragrance and vibrant petals, plumeria blooms remind us to embrace happiness and live life to the fullest.",
    title_3: "🌞You are someone who radiates warmth, who turns ordinary days into something special, and who spreads joy like the ocean breeze.",
    title_4: "✨Wish you endless laughter, sun-kissed adventures, and a life that feels like a permanent summer.",
  },
  {
    flower: "Lavender",
    title_1: "💜This is the flower of calm and healing.",
    title_2: "🌿Known for its soothing scent and calming properties, lavender is a reminder that peace is always within reach.",
    title_3: "🧘‍♀️You are someone who brings tranquility wherever you go, who heals with your presence, and who finds beauty in the quiet moments.",
    title_4: "🌌Wish you a life filled with serenity, a heart that always feels at home, and the kind of healing that only comes from within.",
  },
  {
    flower: "Rosemary",
    title_1: "🌿This is the flower of memory and wisdom.",
    title_2: "🌱With its earthy scent and healing properties, rosemary has long been a symbol of deep remembrance and knowledge.",
    title_3: "📖You are someone who carries the past with grace, learns from every experience, and shares wisdom effortlessly.",
    title_4: "💫Wish you a future where every lesson turns into strength, every memory becomes a treasure, and your knowledge lights the way for others.",
  },
  {
    flower: "Bluebell",
    title_1: "🔔This is the flower of humility and everlasting love.",
    title_2: "🌾Delicate yet resilient, bluebells bow gently in the wind, symbolizing quiet strength and devotion.",
    title_3: "🌊You are someone who leads with kindness, whose love is deep and unwavering, and who finds beauty in the smallest things.",
    title_4: "💙Wish you a heart that stays gentle, love that stands the test of time, and a soul that always feels deeply connected to the world around you.",
  },
  {
    flower: "Magnolia",
    title_1: "🌳This is the flower of grace and strength.",
    title_2: "🌿With its timeless beauty and sturdy roots, the magnolia proves that true elegance comes from resilience.",
    title_3: "🌙You are someone who carries yourself with quiet power. Soft yet unshakable, kind yet strong, you are both gentle and fierce in the best way.",
    title_4: "💫Wish you a future where your inner strength guides you, where grace is your greatest weapon, and where you bloom fearlessly.",
  },
  {
    flower: "Daffodil",
    title_1: "🌿This is the flower of renewal and optimism.",
    title_2: "🌾Blooming at the first sign of spring, daffodils are a symbol of fresh starts, brighter days, and the promise of something wonderful ahead.",
    title_3: "🌟You are someone who carries hope wherever you go. Your energy is uplifting, your spirit unstoppable, and your heart always open to new possibilities.",
    title_4: "🌈Wish you a life where every morning feels like a fresh start, where happiness follows you like sunshine, and where your dreams bloom effortlessly.",
  },
  {
    flower: "Love in a Mist (Devil in the Bush)",
    title_1: "🌫️This is the flower of mystery and hidden love.",
    title_2: "💙Delicate yet surrounded by a mist of fine leaves, this flower reminds us that the most precious things are sometimes veiled in mystery.",
    title_3: "✨You are someone who holds depth beyond what meets the eye. A heart full of untold stories, a soul wrapped in quiet magic.",
    title_4: "🌌Wish you love that finds you unexpectedly, dreams that unfold beautifully, and moments that feel like destiny revealing itself.",
  },
  {
    flower: "Surprise Lily",
    title_1: "🌿This is the flower of unexpected joy and reunion.",
    title_2: "🔥Blooming suddenly, long after its leaves disappear, the Surprise Lily reminds us that beauty often comes when we least expect it.",
    title_3: "🌟You are someone who brings light into people’s lives in the most unexpected ways. Your presence is a gift, your timing always just right.",
    title_4: "🌈Wish you surprises that bring happiness, reunions that warm your heart, and a life filled with wonderful, unexpected turns.",
  },
  {
    flower: "Chocolate Cosmos",
    title_1: "🍫This is the flower of deep attraction and sweet memories.",
    title_2: "🌑With petals as rich as velvet and a scent like chocolate, this rare flower reminds us that some connections are irresistibly sweet and unforgettable.",
    title_3: "💖You are someone who leaves an impression that lingers. Mysterious, warm, and captivating—people can’t help but be drawn to you.",
    title_4: "✨Wish you love that is rich and deep, moments that taste like your favorite memories, and a heart forever full of warmth.",
  },
  {
    flower: "Kadupul Flower",
    title_1: "🌙This is the flower of fleeting beauty and divine rarity.",
    title_2: "🌿Blooming only at night and fading before dawn, the Kadupul Flower is so rare and delicate that it cannot be owned—only experienced.",
    title_3: "💫You are someone who carries an untouchable grace. Ethereal, one-of-a-kind, impossible to capture yet unforgettable.",
    title_4: "🌌Wish you moments so beautiful they take your breath away, dreams that come alive in the night, and a soul that remains forever free.",
  },
  {
    flower: "Jade Vine",
    title_1: "🦋This is the flower of enchantment and resilience.",
    title_2: "🌿With its luminous turquoise petals and otherworldly glow, the Jade Vine thrives in wild rainforests, symbolizing rare beauty and perseverance.",
    title_3: "🌊You are someone who stands out in a world of ordinary. Unconventional, strong, and deeply captivating.",
    title_4: "💙Wish you a journey where you shine in your own unique way, where challenges only make you stronger, and where magic follows wherever you go.",
  },
  {
    flower: "Persian Lily",
    title_1: "🌺This is the flower of elegance and quiet strength.",
    title_2: "🌿Once treasured by ancient kings, the Persian Lily carries an air of regal beauty, standing tall even in harsh conditions.",
    title_3: "👑You are someone with an inner grace that commands respect. Unshaken by storms, you rise with dignity and charm.",
    title_4: "✨Wish you a life filled with effortless elegance, strength that never wavers, and a future as grand as your spirit.",
  },
  {
    flower: "Snake’s Head Fritillary",
    title_1: "🎭This is the flower of uniqueness and quiet resilience.",
    title_2: "🌿Its checkered petals, rare and unusual, remind us that beauty isn’t always conventional—it’s found in the bold and different.",
    title_3: "🖤You are someone who embraces what makes you different. A little mysterious, undeniably striking, and always standing strong in your own way.",
    title_4: "💫Wish you the courage to walk your own path, confidence in what sets you apart, and a world that finally sees your true beauty.",
  },
  {
    flower: "Camellia ‘Middlemist’s Red’",
    title_1: "🌹This is the flower of rarity and timeless love.",
    title_2: "🌿One of the rarest flowers in the world, Middlemist’s Red symbolizes love so strong, it defies time and space.",
    title_3: "❤️You are someone whose presence is precious. Deeply valued, deeply loved, and unforgettable in every way.",
    title_4: "✨Wish you a love that lasts lifetimes, moments that feel eternal, and a heart that knows its own worth.",
  }
]
